require('plugins-configs.alpha')
require('plugins-configs.telescope')
require('plugins-configs.bufferline')
require('plugins-configs.lualine')
require('plugins-configs.toggleterm')
require('plugins-configs.mason')
require('plugins-configs.lsp-zero')
